server:
  port: 8081
spring:
  application:
    name: courses-service
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    url: ${DB_HOST:jdbc:mysql://localhost:3306/courses_db}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
students-service:
  url: ${STUDENTS_URL:http://localhost:8080}

